version: "3.9"
services:
  db:
    container_name: postgresql
    image: postgres
    ports:
      - "${POSTGRES_EXPOSED_PORT}:${POSTGRES_INTERNAL_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}